### ISSUE TITLE
[ERROR]  /home/ec2-user/lib/utils.sh: No such file or directory

### ISSUE THREAD

**Issue by devops-inthe-east** [HariSekhon/DevOps-Bash-tools#13]
This is when I try running scripts in the kubernetes folder . 

::DEBUG OUTPUT ::

sh k1.sh
+++ dirname k1.sh
++ cd .
++ pwd
+ srcdir=/home/ec2-user
+ . /home/ec2-user/lib/utils.sh
k1.sh: line 25: /home/ec2-user/lib/utils.sh: No such file or directory

**Comment by HariSekhon** [comment]
Read the readme, you need to clone the repo and run it from the checkout because lots of scripts use libs and adjacent scripts for code reuse

**Comment by devops-inthe-east** [comment]
Thanks Hari for your response!
