### ISSUE TITLE
templates broke Debian

### ISSUE THREAD

**Issue by dotysan** [HariSekhon/DevOps-Bash-tools#15]
This commit broke CI.

https://github.com/HariSekhon/DevOps-Bash-tools/commit/da278a05823c78709d831a4e6ba9cce4e5a481a7

For all the Debian distros.

 - https://github.com/HariSekhon/DevOps-Bash-tools/actions/runs/8022094483/job/21915649211#step:30:394
 - https://github.com/HariSekhon/DevOps-Bash-tools/actions/runs/8022094512/job/21915648159#step:30:394
 - https://github.com/HariSekhon/DevOps-Bash-tools/actions/runs/8022094478/job/21915649443#step:30:394
 - https://github.com/HariSekhon/DevOps-Bash-tools/actions/runs/8022094487/job/21915650360#step:30:394

```
================================================================================
                         Finding Non Executable Scripts
================================================================================
PROJECT: bash-tools
(running inside docker)

/__w/DevOps-Bash-tools/DevOps-Bash-tools/templates/template.expect

FAILED: non-executable scripts detected!
make: *** [Makefile:312: test] Error 1
Error: Process completed with exit code 2.
```

**Comment by HariSekhon** [comment]
I've updated the submodule version to pull a newer version where the mode is set properly, this has fixed it. Thanks for raising.
